server:
  port: 9000

eureka:
  instance:
    #eureka的自我保护的心跳机
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

    hostname: 127.0.0.1
    port: 8761

  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

spring:
  application:
    name: inc-sso-biz